### ISSUE TITLE
issue while building drivers for RTL8852BE in arch linux

### ISSUE THREAD

**Issue by saifanidk** [morrownr/rtw89#106]
so i use zen kernel because it is fast 

sudo dkms install $PWD
Creating symlink /var/lib/dkms/rtw89/7.2/source -> /usr/src/rtw89-7.2

Sign command: /usr/lib/modules/7.0.14-zen1-1-zen/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s).....(bad exit status: 2)
Failed command:
KVER=7.0.14-zen1-1-zen 'make' modules

Error! Bad return status for module build on kernel: 7.0.14-zen1-1-zen (x86_64)
Consult /var/lib/dkms/rtw89/7.2/build/make.log for more information.

if you want anymore info ask me i will put the log in

[make.log](https://github.com/user-attachments/files/29560745/make.log)

**Comment by dubhater** [comment]
```
In function ‘le32_encode_bits’,
    inlined from ‘rtw89_fw_cmd_ofld_enqueue’ at fw.c:11655:12,
    inlined from ‘rtw89_fw_cmd_ofld_udelay’ at fw.c:11858:8:
/usr/lib/modules/7.0.14-zen1-1-zen/build/include/linux/bitfield.h:217:17: error: call to ‘__field_overflow’ declared with attribute error: value doesn't fit into mask
```

It's not wrong. RTW89_FW_CMD_OFLD_SRC_OTHER has the value 4, which doesn't fit in the mask RTW89_H2C_CMD_OFLD_W0_SRC. But why don't I get this error on 7.0.12-arch1-1?

**Comment by saifanidk** [comment]
idk

**Comment by saifanidk** [comment]
i use hp laptop btw

**Comment by saifanidk** [comment]
the problem is zen kernel i reinstalled arch linux with the default kernel and it worked

**Comment by saifanidk** [comment]
and also if i download a large file example 250 gb or more wifi stops working

**Comment by a5a5aa555oo** [comment]
@saifanidk 

Actually you dont need this driver, there is a built-in rtw89 driver in your kernel. Doesn't it work?

**Comment by saifanidk** [comment]
same issue keeps disconnecting

**Comment by saifanidk** [comment]
that is why i switched to this driver but same issue

**Comment by a5a5aa555oo** [comment]
try the workaround below

https://github.com/morrownr/rtw89/issues/98#issuecomment-4619148246

**Comment by saifanidk** [comment]
tysm
