### ISSUE TITLE
Linux 7.1.x build failure (__field_overflow) + RTL8852BU (35bc:0100) regression

### ISSUE THREAD

**Issue by hafezsamy** [morrownr/rtw89#112]
## Environment

* Distribution: Nobara Linux 44 (Fedora 44 based)
* Kernel: 7.1.3-200.nobara.fc44.x86_64
* Architecture: x86_64
* Adapter:

  * USB VID:PID = 35bc:0100
  * Chipset: RTL8852BU

## Summary

I upgraded from Nobara 43 to Nobara 44.

My RTL8852BU adapter works perfectly on kernel:

* 7.0.9-200.nobara.fc43.x86_64
* 7.0.11-200.nobara.fc43.x86_64

After upgrading to:

* 7.1.3-200.nobara.fc44.x86_64

the in-kernel rtw89 driver no longer works reliably.

Symptoms:

* Wi-Fi disconnects under load.
* Speedtest download immediately fails.
* NetworkManager disconnects the interface.
* dmesg reports:

  * Update probe request failed
  * c2h reg timeout
  * timed out to flush queues

I attempted to test the latest out-of-tree rtw89 driver to determine whether the issue was already fixed upstream.

The latest repository (HEAD d90b0df) does not build on Linux 7.1.3.

Build command:

```bash
make clean modules && sudo make install
```
Compilation fails in fw.c:

```text
error: call to '__field_overflow' declared with attribute error:
value doesn't fit into mask
```
Location:

```
fw.c
rtw89_fw_cmd_ofld_enqueue()
```
The compiler reports:

```
include/linux/bitfield.h
le32_encode_bits()
```

This appears to be caused by a Linux 7.1 API or compile-time validation change.

## Additional information

Firmware loads correctly:

```
rtw89_8852bu ... loaded firmware rtw89/rtw8852b_fw-2.bin
```

The adapter is detected correctly:

```
35bc:0100
```

Kernel module:

```
rtw89_8852bu
```

No external DKMS Realtek driver is installed.

## Questions

1. Is Linux 7.1.x currently supported by this repository?
2. Is there already a patch available for the fw.c compile failure?
3. Has anyone reported RTL8852BU runtime regressions on Linux 7.1.x similar to:

   * Update probe request failed
   * c2h reg timeout
   * timed out to flush queues

**Comment by dubhater** [comment]
We know about both problems.

You can try this for the compilation error:

```diff
diff --git a/fw.c b/fw.c
index 5001b22..82e03ea 100644
--- a/fw.c
+++ b/fw.c
@@ -11849,7 +11849,7 @@ static void rtw89_fw_cmd_ofld_write_rf(struct rtw89_dev *rtwdev,
 static void rtw89_fw_cmd_ofld_udelay(struct rtw89_dev *rtwdev, u32 us)
 {
 	struct rtw89_fw_cmd_ofld_arg cmd = {
-		.src = RTW89_FW_CMD_OFLD_SRC_OTHER,
+		.src = RTW89_FW_CMD_OFLD_SRC_BB,
 		.type = RTW89_FW_CMD_OFLD_DELAY,
 		.value = us,
 	};
@@ -11863,7 +11863,7 @@ static void rtw89_fw_cmd_ofld_udelay(struct rtw89_dev *rtwdev, u32 us)
 static void rtw89_fw_cmd_ofld_mdelay(struct rtw89_dev *rtwdev, u32 ms)
 {
 	struct rtw89_fw_cmd_ofld_arg cmd = {
-		.src = RTW89_FW_CMD_OFLD_SRC_OTHER,
+		.src = RTW89_FW_CMD_OFLD_SRC_BB,
 		.type = RTW89_FW_CMD_OFLD_DELAY,
 		.value = ms * 1000,
 	};
```

**Comment by hafezsamy** [comment]
the compiler issue is gone but i still have this issue for my TP-Link Archer TX20U Plus wifi adapter 
Wi-Fi disconnects under load.
Speedtest  using fails  Internet Disconnects But WiFi Stays Connected

**Comment by a5a5aa555oo** [comment]
@dubhater has asked stable kernel maintainers to apply [the fix](https://github.com/torvalds/linux/commit/63ccdfac8677387dfdbd9d4336089e9823280704) to kernel 7.1 and it will be in 7.1.4 or 7.1.5.

https://lore.kernel.org/stable/083f380c-23e3-4a46-9885-085013371aee@gmail.com/

**Comment by hafezsamy** [comment]
still facing the same issue after upgrade to 

7.1.4-200.nobara.fc44.x86_64 kernel

My TP-Link Archer TX20U Internet Disconnects But WiFi Stays Connected and i must Disconnect the WiFi and reconnect again multiple times to get it to work

I'm using the in kernel driver and the same issue when using the out of kernel driver rtw89

lsmod | grep rtw89

rtw89_8852bu           12288  0
rtw89_8852b           352256  1 rtw89_8852bu
rtw89_8852b_common     65536  1 rtw89_8852b
rtw89_usb              36864  1 rtw89_8852bu
rtw89_core           1388544  3 rtw89_8852b,rtw89_8852b_common,rtw89_usb
mac80211             1912832  2 rtw89_core,rtw89_usb
cfg80211             1626112  3 rtw89_core,mac80211,rtw89_8852b_common
rfkill                 45056  8 rtw89_core,bluetooth,cfg80211

plz if anyone can help

**Comment by a5a5aa555oo** [comment]
@hafezsamy 

Maybe you can try the rtw89 v7.0 to see if it works well on you side.

Steps to install rtw89 v7.0
1. [uninstall the out-of-kernel rtw89 driver installed on your system](https://github.com/morrownr/rtw89/blob/main/README.md#uninstallation-guide)
2. Clone the  driver
```
cd /tmp && git clone https://github.com/morrownr/rtw89
```
3. Restore the source code to v7.0
```
cd rtw89 
```
```
git reset --hard c121a6a
```
4. Install the v7.0  driver 
```
make clean modules && sudo make install
```
```
sudo cp rtw89.conf /etc/modprobe.d/
```
5. reboot

**Comment by hafezsamy** [comment]
@a5a5aa555oo , it's the same issue, the internet still disconnect but the wifi is connected
also find below maybe it will help

on 7.0.11-200.nobara.fc43.x86_64 kernel i was using this driver https://github.com/morrownr/rtl8852bu-20250826 and works perfectly

but it stopped working on below kernels, it just freezes the entire system and i had to use the in-kernel driver or the rtw89 driver

7.1.3-200.nobara.fc44.x86_64
7.1.4-200.nobara.fc44.x86_64

**Comment by a5a5aa555oo** [comment]
@hafezsamy 

Please attatch the full kernel log (dmesg.txt)
```
sudo dmesg > dmesg.txt
```

**Comment by hafezsamy** [comment]
@a5a5aa555oo kindly find the attached file

[dmesg.txt](https://github.com/user-attachments/files/30220548/dmesg.txt)

it works fine when connected to 2.4GHz network, but the issue happen when connected to 5GHz 
for both i'm using a usb 3 port

find attached file when using 2.4GHz wifi and perform the test, it's also contains logs when connected 5GHz wifi and make a speed test

[dmesg-2.4GHz.txt](https://github.com/user-attachments/files/30231885/dmesg-2.4GHz.txt)

**Comment by a5a5aa555oo** [comment]
My only suggestion is..try other USB2.0/3.x ports.

I have a TP-Link TX20U (35bc:0100) too. Recently i tested it on Arch Linux and Nobara 44 with kernel 7.0.x and 7.1.x but i can't produce this problem at all..

**Comment by hafezsamy** [comment]
On Nobara 44 with kernel 7.0.x i was using this driver https://github.com/morrownr/rtl8852bu-20250826 and it was working fine on the same port, it stopped working after upgrading to 7.1.x

**Comment by a5a5aa555oo** [comment]
@hafezsamy 

Still remember which mode the dongle was in when using https://github.com/morrownr/rtl8852bu-20250826 ? USB2 or USB3 ?
Does wifi work better if you [force the adapter to stay in USB2 mode](https://github.com/morrownr/rtw89#q7-my-computer-only-provides-usb-3x-ports-how-can-i-make-my-usb-wireless-adapter-work-in-usb-20-mode)?

$ lsusb -t
...
/:  Bus 009.Port 001: Dev 001, Class=root_hub, Driver=xhci_hcd/2p, 5000M
    |__ Port 002: Dev 002, If 0, Class=Vendor Specific Class, Driver=rtw89_8852bu_git, **5000M**

**5000M** or a speed greater than 5000M means the adapter is in USB3 mode, **480M** means USB2 mode.

**Comment by hafezsamy** [comment]
@a5a5aa555oo when using https://github.com/morrownr/rtl8852bu-20250826 the mode was USB3 
from the 8852bu.conf file, always changed below to 1

options 8852bu rtw_switch_usb_mode=1
